# Generated by Django 4.1.5 on 2023-02-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="card_img",
            field=models.ImageField(
                blank=True, default="note/images/no-image.png", upload_to=""
            ),
        ),
    ]
