# Generated by Django 4.1.5 on 2023-02-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganizerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254)),
                ("profile_pic", models.ImageField(upload_to="profile_pics")),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254)),
                ("registration_no", models.CharField(max_length=50, unique=True)),
                ("profile_pic", models.ImageField(upload_to="profile_pics")),
            ],
        ),
    ]
